### ISSUE TITLE
README still instructs to install gtk+3

### ISSUE THREAD

**Issue by oakes** [TingPing/homebrew-gnome#5]
I noticed you removed gtk+3, so perhaps the README should be changed. Also, can you explain why it was removed? Is there another way to get the Quartz version of it now?

**Comment by TingPing** [comment]
@oakes The main gtk packages in the official homebrew repo now work with ```--without-x11```

**Comment by oakes** [comment]
I tried `brew install gtk+3 --without-X11` earlier today and it said XQuartz is required. Is this expected? I didn't need XQuartz before so I was confused.

**Comment by TingPing** [comment]
Ah right, forgot about that. This is a homebrew bug (maybe it is not reported upstream).

1. Run ```brew edit gtk+3```
2. Find the line ```depends_on "at-spi2-atk" if build.with? "x11"```
3. Comment it out (start line with a #)

**Comment by oakes** [comment]
I see. I suppose I'll upload the version with that change added to my own repo so others can install it more easily. Thanks

**Comment by TingPing** [comment]
I'll try to report this upstream, it has been a bug since I started using homebrew =\

**Comment by TingPing** [comment]
Opened https://github.com/Homebrew/homebrew/issues/36915

**Comment by oakes** [comment]
Thanks. However, it looks like that isn't the only issue. The error still appears after commenting the line, because it seems that pango and cairo also think they need X11:

```
gtk+3: XQuartz 2.5 is required to install this formula.
You can install with Homebrew Cask:
  brew install Caskroom/cask/xquartz

You can download from:
  https://xquartz.macosforge.org
cairo: XQuartz is required to install this formula.
You can install with Homebrew Cask:
  brew install Caskroom/cask/xquartz

You can download from:
  https://xquartz.macosforge.org
pango: XQuartz is required to install this formula.
You can install with Homebrew Cask:
  brew install Caskroom/cask/xquartz

You can download from:
  https://xquartz.macosforge.org
```

**Comment by TingPing** [comment]
Install each of them with ```--without-x11```. None of them should require modification iirc.
